/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CarCatalog;
import model.Cars;

/**
 *
 * @author susan
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    CarCatalog carCatalog;
    private Object c;
    private Object car;
    private String[] row;
    public ViewJPanel(CarCatalog carCatalog) {
        initComponents();
        
        this.carCatalog = carCatalog;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Price", "Make", "Model", "Year", "Seat", "Serial Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jButton1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int selectedRowIndex = jTable1.getSelectedRow();
        
        row[0] = model.getValueAt(selectedRowIndex, 0).toString();
        row[1] = model.getValueAt(selectedRowIndex, 1).toString();
        row[2] = model.getValueAt(selectedRowIndex, 2).toString();
        row[3] = model.getValueAt(selectedRowIndex, 3).toString();
        row[4] = model.getValueAt(selectedRowIndex, 4).toString();
        row[5] = model.getValueAt(selectedRowIndex, 5).toString();
        
        
        
        row[0] =JOptionPane.showInputDialog(null,(row[0]));
         row[1] =JOptionPane.showInputDialog(null,(row[1]));
        row[2] =JOptionPane.showInputDialog(null,(row[2]));
         row[3] =JOptionPane.showInputDialog(null,(row[3]));
         row[4] =JOptionPane.showInputDialog(null,(row[4]));
         row[5] =JOptionPane.showInputDialog(null,(row[5]));
         
         
         model.setValueAt((row[0]), selectedRowIndex, 0);
          model.setValueAt((row[1]), selectedRowIndex, 1);
          model.setValueAt((row[2]), selectedRowIndex, 2);
          model.setValueAt((row[3]), selectedRowIndex, 3);
          model.setValueAt((row[4]), selectedRowIndex, 4);
          model.setValueAt((row[5]), selectedRowIndex, 5);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        
        for(Cars c : carCatalog.getCarcatalog()){
        
        Object[] row = new Object[6];
        row[0] = c.getPrice();
        row[1] = c.getMake();
        row[2] = c.getModel();
        row[3] = c.getYear();
        row[4] = c.getSeat();
        row[5] = c.getSerialnumber();
       
        model.addRow(row);
    }
        
        
        
    }
}
